version: '1'

services:
  react:
    container_name: react_test    
    build:
        dockerfile: Dockerfile
        context: ./        
    volumes:
        - ./:/app
    ports:
        - "3333:80"
 

